apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-sm
    kind: ClusterSecretStore
  target:
    name: hetzner-s3
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: name:familiar-systems-preview-key
        property: access_key_id
        version: latest_enabled
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: name:familiar-systems-preview-key
        property: secret_access_key
        version: latest_enabled
