apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: internal-bearer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-sm
    kind: ClusterSecretStore
  target:
    name: internal-bearer
    creationPolicy: Owner
  data:
    - secretKey: INTERNAL_BEARER_PRIMARY
      remoteRef:
        key: name:internal-bearer-preview
        version: latest_enabled
