#!/usr/bin/env bash
# generate-imports.sh -- Reads a Pulumi state export and generates imports.tf
#
# Usage:
#   cd infra/pulumi-cloud
#   source .envrc
#   pulumi stack export --stack prod > /tmp/pulumi-state.json
#   cd ../tofu
#   ./scripts/generate-imports.sh /tmp/pulumi-state.json
#
# Output: writes imports.tf in the current directory.
# After running: tofu plan  (should show imports + zero changes)
#                tofu apply  (performs the imports)
#                rm imports.tf                     (no longer needed)

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <pulumi-state-export.json>" >&2
    exit 1
fi

STATE_FILE="$1"
if [[ ! -f "${STATE_FILE}" ]]; then
    echo "Error: ${STATE_FILE} not found" >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "Error: jq is required" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMPORTS_FILE="${SCRIPT_DIR}/../imports.tf"

# Extract resources from the Pulumi state. Each resource has:
#   .urn  (pulumi URN)
#   .id   (provider-specific ID)
#   .type (pulumi type token)

echo "==> Parsing Pulumi state export..."

# Build a mapping of Pulumi type::name -> (tofu_address, id_expression)
# We extract the ID from the state for each known resource.

cat > "${IMPORTS_FILE}" << 'HEADER'
# Generated by scripts/generate-imports.sh from Pulumi state export.
# Delete this file after running: tofu apply

HEADER

extract_id() {
    local type="$1"
    local urn_suffix="$2"
    jq -r --arg type "$type" --arg suffix "$urn_suffix" '
        .deployment.resources[]
        | select(.type == $type and (.urn | endswith($suffix)))
        | .id // empty
    ' "${STATE_FILE}" | head -1
}

emit_import() {
    local tofu_addr="$1"
    local id="$2"
    if [[ -n "${id}" ]]; then
        echo "import {"
        echo "  to = ${tofu_addr}"
        echo "  id = \"${id}\""
        echo "}"
        echo ""
    else
        echo "# WARNING: could not find ID for ${tofu_addr}" >&2
    fi
}

{
    echo "# --- Hetzner Cloud ---"
    echo ""

    id=$(extract_id "hcloud:index/sshKey:SshKey" "personal-ssh-key")
    emit_import "hcloud_ssh_key.personal" "$id"

    id=$(extract_id "hcloud:index/sshKey:SshKey" "deploy-ssh-key")
    emit_import "hcloud_ssh_key.deploy" "$id"

    id=$(extract_id "hcloud:index/floatingIp:FloatingIp" "floating-ip")
    emit_import "hcloud_floating_ip.main" "$id"

    id=$(extract_id "hcloud:index/firewall:Firewall" "firewall")
    emit_import "hcloud_firewall.main" "$id"

    # Volume and server are children of the K3sCluster component
    id=$(extract_id "hcloud:index/volume:Volume" "k3s-data-volume")
    emit_import "hcloud_volume.data" "$id"

    id=$(extract_id "hcloud:index/server:Server" "k3s-server")
    emit_import "hcloud_server.k3s" "$id"

    # Floating IP assignment
    id=$(extract_id "hcloud:index/floatingIpAssignment:FloatingIpAssignment" "k3s-fip-assignment")
    emit_import "hcloud_floating_ip_assignment.main" "$id"

    # Volume attachment
    id=$(extract_id "hcloud:index/volumeAttachment:VolumeAttachment" "k3s-volume-attachment")
    emit_import "hcloud_volume_attachment.data" "$id"

    echo "# --- Scaleway IAM ---"
    echo ""

    # Registry namespace: try Pulumi state, fall back to scw CLI
    id=$(extract_id "scaleway:index/registryNamespace:RegistryNamespace" "container-registry")
    if [[ -z "$id" ]]; then
        id=$(scw registry namespace list -o json | jq -r '.[] | select(.name == "loreweaver") | .id')
    fi
    emit_import "scaleway_registry_namespace.main" "fr-par/${id}"

    # IAM resources: resolve by name via scw CLI (Pulumi type tokens vary
    # across pulumiverse-scaleway versions, so CLI lookup is more reliable)
    echo "    Resolving IAM resources via scw CLI..." >&2

    reg_pull_app_id=$(scw iam application list -o json | jq -r '.[] | select(.name == "k3s-registry-puller") | .id')
    emit_import "scaleway_iam_application.registry_pull" "$reg_pull_app_id"

    eso_app_id=$(scw iam application list -o json | jq -r '.[] | select(.name == "k3s-external-secrets") | .id')
    emit_import "scaleway_iam_application.eso" "$eso_app_id"

    id=$(scw iam policy list -o json | jq -r '.[] | select(.name == "k3s-registry-puller") | .id')
    emit_import "scaleway_iam_policy.registry_pull" "$id"

    id=$(scw iam policy list -o json | jq -r '.[] | select(.name == "k3s-external-secrets") | .id')
    emit_import "scaleway_iam_policy.eso" "$id"

    id=$(scw iam api-key list -o json | jq -r --arg app "$reg_pull_app_id" '.[] | select(.application_id == $app) | .access_key')
    emit_import "scaleway_iam_api_key.registry_pull" "$id"

    id=$(scw iam api-key list -o json | jq -r --arg app "$eso_app_id" '.[] | select(.application_id == $app) | .access_key')
    emit_import "scaleway_iam_api_key.eso" "$id"

    echo "# --- Scaleway Secrets ---"
    echo ""

    # Secrets: resolve by name via scw CLI
    echo "    Resolving SM secrets via scw CLI..." >&2

    scw_secret_id() {
        local name="$1"
        scw secret secret list "name=${name}" region=fr-par -o json | jq -r '.[0].id // empty'
    }

    for pair in \
        "loreweaver-deploy-ssh-key|scaleway_secret.deploy_ssh" \
        "bunny-api-key|scaleway_secret.bunny_api_key" \
        "k3s-kubeconfig|scaleway_secret.k3s_kubeconfig" \
        "internal-bearer-prod|scaleway_secret.internal_bearer_prod" \
        "internal-bearer-preview|scaleway_secret.internal_bearer_preview" \
        "eso-scaleway-credential|scaleway_secret.eso_credential" \
        "registry-pull-credential|scaleway_secret.registry_pull_credential" \
    ; do
        sm_name="${pair%%|*}"
        tofu_addr="${pair#*|}"
        id=$(scw_secret_id "$sm_name")
        emit_import "$tofu_addr" "fr-par/${id}"
    done

    # Secret versions: look up latest revision for the two OpenTofu-written secrets
    scw_secret_version_id() {
        local name="$1"
        local secret_id
        secret_id=$(scw_secret_id "$name")
        local revision
        revision=$(scw secret version list "secret-id=${secret_id}" region=fr-par -o json \
            | jq -r 'sort_by(.revision) | last | .revision // empty')
        echo "${secret_id}/${revision}"
    }

    id=$(scw_secret_version_id "eso-scaleway-credential")
    emit_import "scaleway_secret_version.eso_credential" "fr-par/${id}"

    id=$(scw_secret_version_id "registry-pull-credential")
    emit_import "scaleway_secret_version.registry_pull_credential" "fr-par/${id}"

    echo "# --- Hetzner Object Storage (minio) ---"
    echo ""

    emit_import "minio_s3_bucket.prod" "familiar-systems-prod"
    emit_import "minio_s3_bucket.preview" "familiar-systems-preview"

    # Bucket policies import by bucket name
    emit_import "minio_s3_bucket_policy.prod" "familiar-systems-prod"
    emit_import "minio_s3_bucket_policy.preview" "familiar-systems-preview"

    # Versioning imports by bucket name
    emit_import "minio_s3_bucket_versioning.prod" "familiar-systems-prod"

    # ILM policies: need bucket/rule-id. Extract from state if possible,
    # otherwise use known rule IDs.
    emit_import "minio_ilm_policy.prod" "familiar-systems-prod"
    emit_import "minio_ilm_policy.preview" "familiar-systems-preview"

    echo "# --- New resource (not imported, created fresh) ---"
    echo "# scaleway_secret.hcloud_api_token is new; OpenTofu will create it."
    echo "# If you already created it via scw CLI, add an import block:"
    echo "# import {"
    echo "#   to = scaleway_secret.hcloud_api_token"
    echo "#   id = \"fr-par/<secret-id>\""
    echo "# }"

} >> "${IMPORTS_FILE}"

echo "==> Generated ${IMPORTS_FILE}"
echo ""
echo "Next steps:"
echo "  1. Review imports.tf for any WARNING lines"
echo "  2. tofu plan"
echo "  3. Iterate on .tf files until plan shows zero changes"
echo "  4. tofu apply"
echo "  5. rm imports.tf"
