#!/usr/bin/env bash
# Per-machine setup: generates .envrc from existing Scaleway resources.
# Run this on any new machine after scw init.
#
# The Scaleway provider reads credentials from ~/.config/scw/config.yaml
# directly, so only the S3 backend and state encryption need env vars.
# The hcloud and minio providers self-serve their credentials from
# Scaleway SM via ephemeral resources at tofu runtime (see providers.tf).
#
# Prerequisites:
#   - scw CLI installed and configured (scw init)
#   - jq installed
#   - direnv installed
#
# Usage: ./scripts/setup.sh

set -euo pipefail

for tool in jq scw direnv; do
    if ! command -v "$tool" > /dev/null 2>&1; then
        echo "Error: ${tool} is not installed." >&2
        exit 1
    fi
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

BUCKET_NAME="familiar-systems-tofu-state"
REGION="fr-par"
PASSPHRASE_SECRET="tofu-config-passphrase"

# --- Verify resources exist ---
echo "==> Verifying Scaleway resources"

if ! scw object bucket list region="${REGION}" -o json | jq -e ".[] | select(.Name == \"${BUCKET_NAME}\")" > /dev/null 2>&1; then
    echo "Error: Bucket '${BUCKET_NAME}' not found in ${REGION}. Run scripts/bootstrap.sh first." >&2
    exit 1
fi
echo "    Bucket: ${BUCKET_NAME}"

fetch_secret_value() {
    local name="$1"
    local secret_id
    secret_id=$(scw secret secret list "name=${name}" "region=${REGION}" -o json | jq -r '.[0].id // empty')
    if [ -z "${secret_id}" ]; then
        echo "Error: Secret '${name}' not found in ${REGION}. Run scripts/bootstrap.sh first." >&2
        exit 1
    fi
    scw secret version access "${secret_id}" revision=latest "region=${REGION}" -o json | jq -r '.data' | base64 -d
}

# --- Resolve credentials ---
echo "==> Reading credentials"

SCW_CONFIG="$(scw config dump -o json)"
SCW_PROFILE="$(echo "${SCW_CONFIG}" | jq -r '.active_profile')"
ACCESS_KEY="$(echo "${SCW_CONFIG}" | jq -r --arg p "${SCW_PROFILE}" '.profiles[$p].access_key')"
SECRET_KEY="$(echo "${SCW_CONFIG}" | jq -r --arg p "${SCW_PROFILE}" '.profiles[$p].secret_key')"

PASSPHRASE="$(fetch_secret_value "${PASSPHRASE_SECRET}")"

# --- .envrc ---
ENVRC_PATH="${PROJECT_DIR}/.envrc"
echo "==> Generating ${ENVRC_PATH}"

cat > "${ENVRC_PATH}" << EOF
# Auto-generated by scripts/setup.sh -- re-run if credentials change.

# S3 backend auth (Scaleway creds mapped to AWS env vars).
# The Scaleway provider itself reads from ~/.config/scw/config.yaml.
export AWS_ACCESS_KEY_ID="${ACCESS_KEY}"
export AWS_SECRET_ACCESS_KEY="${SECRET_KEY}"

# OpenTofu state encryption
export TF_VAR_state_encryption_passphrase="${PASSPHRASE}"
EOF

echo "    .envrc written."

echo ""
echo "==> Setup complete!"
echo "    Next steps:"
echo "      1. Run 'direnv allow'"
echo "      2. Run 'tofu init'"
