apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bunny-api-key
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-sm
    kind: ClusterSecretStore
  target:
    name: bunny-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: name:bunny-api-key
        version: latest_enabled
