apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: scaleway-sm
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: "${SCW_PROJECT_ID}"
      accessKey:
        secretRef:
          name: eso-scaleway-credentials
          key: access-key
          namespace: external-secrets
      secretKey:
        secretRef:
          name: eso-scaleway-credentials
          key: secret-key
          namespace: external-secrets
