apiVersion: v1
kind: PersistentVolume
metadata:
  name: campaign-pv
  labels:
    app: campaign
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: default
    name: campaign-pvc
  hostPath:
    path: /data/campaigns
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.familiar.systems/role
              operator: In
              values: [platform]
