# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: platform-pv
  resources:
    requests:
      storage: 1Gi
