apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: campaign-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: campaign-pv-${NAMESPACE}
  resources:
    requests:
      storage: 1Gi
