apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-pv-${NAMESPACE}
  labels:
    app: platform
    namespace: ${NAMESPACE}
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: ${NAMESPACE}
    name: platform-pvc
  hostPath:
    path: /data/preview/${NAMESPACE}/platform
    type: DirectoryOrCreate
