apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site
  namespace: ${NAMESPACE}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - ${PR_HOST}
      secretName: preview-wildcard-tls
  rules:
    - host: ${PR_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: site
                port:
                  number: 80
