// File-based TanStack Router setup for the SPA. The route tree is
// generated by @tanstack/router-plugin/vite from src/routes/*.tsx; each
// route file owns its component, beforeLoad, parseParams, loader, and
// errorComponent. This file is the assembly point: it wires the
// generated tree into a typed Router singleton and registers it on the
// global Register interface so navigate / Link / useRouteContext calls
// are type-checked across the app.
//
// The router context is supplied externally by App.tsx via
// <RouterProvider context={{ auth }} />. The placeholder { kind:
// 'unauthed' } below is a type-level seed - it never reaches the
// router because App gates RouterProvider's mount on auth resolving.
//
// When adding a route with a branded-ID param, brand the ID at the URL
// boundary in the route file's parseParams, with a Zod schema co-located
// with the brand. Platform-shared brands (CampaignId, UserId) live in
// @familiar-systems/types-app; campaign-only brands (ThingId, BlockId)
// live in @familiar-systems/types-campaign. Example for /campaigns/$id
// (in src/routes/_authed/campaigns/$id.tsx):
//
//   import { campaignIdSchema } from "@familiar-systems/types-app";
//   parseParams: ({ id }) => ({ id: campaignIdSchema.parse(id) }),
//
// Route.useParams() then returns { id: CampaignId }, which flows into
// the typed API client without a cast. lib/api.ts already wires this
// for the platform server (openapi-fetch over PlatformPaths, generated
// from utoipa via tooling/openapi-codegen + ts-rs). The campaign server
// is slated to grow the same pipeline, so the same end-to-end chain
// (URL string, branded ID, typed call) will hold across both servers
// once that lands. parseParams is where brands are minted; the typed
// clients are where they're consumed.

import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// basepath honors per-PR preview prefix (/pr-42/) via Vite's BASE_URL,
// which vite.config.ts feeds from VITE_BASE_PATH. Both <Link> and
// useNavigate respect basepath, so call sites pass logical paths
// ("/settings") and the router prepends the prefix at runtime.
export const router = createRouter({
  routeTree,
  basepath: import.meta.env.BASE_URL,
  context: { auth: { kind: "unauthed" } },
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
