// Codegen script: turns an OpenAPI spec into a typed `paths` interface that
// imports its component schemas from the matching ts-rs output, instead of
// regenerating them locally.
//
// Why the indirection? ts-rs already produces faithful, branded TypeScript
// types for every Rust struct that crosses the wire. OpenAPI's type system
// can't model nominal types (a `format: "uuid"` field is just a string), so
// a vanilla openapi-typescript run would erase our `UserId` brand. The
// transform() hook below intercepts every `#/components/schemas/{Name}`
// definition and replaces it with a TypeScript reference to the same name —
// resolved via an `import type { ... } from "@familiar-systems/types-app"`
// header injected at the top of the file.
//
// Net effect: the generated `paths` interface tells the SPA which routes
// exist and which methods/params/bodies/responses they expect, but every
// component shape resolves to the ts-rs definition. utoipa is the source
// of truth for the URL surface; ts-rs is the source of truth for shapes.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

interface Spec {
  components?: { schemas?: Record<string, unknown> };
}

const TARGETS = {
  platform: {
    spec: "packages/types-app/openapi/platform.json",
    output: "packages/types-app/src/openapi/platform.ts",
    importFrom: "@familiar-systems/types-app",
  },
} as const;

type TargetName = keyof typeof TARGETS;

function isTargetName(value: string): value is TargetName {
  return value in TARGETS;
}

const targetArg = process.argv[2];
if (!targetArg || !isTargetName(targetArg)) {
  console.error(
    `Usage: tsx generate.ts <${Object.keys(TARGETS).join("|")}>`,
  );
  process.exit(1);
}

const target = TARGETS[targetArg];

// Resolve paths relative to the workspace root (two levels up from this
// script). mise tasks invoke us from the workspace root, but we shouldn't
// depend on the caller's CWD.
const workspaceRoot = resolve(import.meta.dirname, "..", "..");
const specPath = resolve(workspaceRoot, target.spec);
const outputPath = resolve(workspaceRoot, target.output);

const spec = JSON.parse(readFileSync(specPath, "utf8")) as Spec;
const componentNames = Object.keys(spec.components?.schemas ?? {}).sort();

// `path` on the transform metadata is the JSON pointer of the schema being
// processed. Top-level component schemas have paths like
// `#/components/schemas/UserId`; nested fields get longer paths like
// `#/components/schemas/MeResponse/properties/email`. We only want to
// rewrite the top-level definitions — nested fields that already $ref a
// known component will be rendered as `components["schemas"]["UserId"]`,
// which resolves through the alias to the imported brand.
const componentPathPattern = /^#\/components\/schemas\/([A-Za-z0-9_]+)$/;

const ast = await openapiTS(spec, {
  transform(_schemaObject, metadata: { path?: string }) {
    const match = metadata.path?.match(componentPathPattern);
    if (!match) return undefined;
    const name = match[1];
    if (!name || !componentNames.includes(name)) return undefined;
    return ts.factory.createTypeReferenceNode(
      ts.factory.createIdentifier(name),
    );
  },
  inject:
    componentNames.length === 0
      ? ""
      : `import type { ${componentNames.join(", ")} } from "${target.importFrom}";`,
});

const banner = [
  "// AUTO-GENERATED by tooling/openapi-codegen.",
  "// Source: cargo run -p familiar-systems-platform --bin emit-openapi",
  "// Do not edit by hand. Run `mise run generate-openapi` to refresh.",
  "",
  "",
].join("\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, banner + astToString(ast));

console.log(
  `Wrote ${outputPath} (${componentNames.length} component schema(s) wired to ${target.importFrom})`,
);
