#!/usr/bin/env bash
# Per-machine setup: generates .envrc from existing Scaleway resources.
# Run this on any new machine after scw init.
#
# Prerequisites:
#   - scw CLI installed and configured (scw init)
#   - jq installed
#   - direnv installed
#
# Usage: ./scripts/setup.sh

set -euo pipefail

if ! command -v jq > /dev/null 2>&1; then
    echo "Error: jq is not installed. Install via 'brew install jq' or your package manager." >&2
    exit 1
fi

if ! command -v scw > /dev/null 2>&1; then
    echo "Error: scw is not installed. Install via 'brew install scw' or see https://github.com/scaleway/scaleway-cli" >&2
    exit 1
fi

if ! command -v direnv > /dev/null 2>&1; then
    echo "Error: direnv is not installed. Install via 'brew install direnv' or see https://direnv.net" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

BUCKET_NAME="loreweaver-pulumi-state"
REGION="fr-par"
SECRET_NAME="pulumi-config-passphrase"
S3_ENDPOINT="s3.${REGION}.scw.cloud"

# --- Verify resources exist ---
echo "==> Verifying Scaleway resources"

if ! scw object bucket list region="${REGION}" -o json | jq -e ".[] | select(.Name == \"${BUCKET_NAME}\")" > /dev/null 2>&1; then
    echo "Error: Bucket '${BUCKET_NAME}' not found in ${REGION}. Run scripts/bootstrap.sh first." >&2
    exit 1
fi
echo "    Bucket: ${BUCKET_NAME}"

SECRET_ID=$(scw secret secret list name="${SECRET_NAME}" region="${REGION}" -o json | jq -r '.[0].id // empty')
if [ -z "${SECRET_ID}" ]; then
    echo "Error: Secret '${SECRET_NAME}' not found in ${REGION}. Run scripts/bootstrap.sh first." >&2
    exit 1
fi
echo "    Secret: ${SECRET_NAME} (${SECRET_ID})"

# --- .envrc ---
ENVRC_PATH="${PROJECT_DIR}/.envrc"
echo "==> Generating ${ENVRC_PATH}"

cat > "${ENVRC_PATH}" << EOF
# Auto-generated by scripts/setup.sh
# Pulls Pulumi config from Scaleway at cd-time via direnv.

# Scaleway credentials come from ~/.config/scw/config.yaml (scw init).
# We need them as AWS_* env vars for Pulumi's S3-compatible backend.
SCW_CONFIG="\$(scw config dump -o json)"
SCW_PROFILE="\$(echo "\${SCW_CONFIG}" | jq -r '.active_profile')"
export AWS_ACCESS_KEY_ID="\$(echo "\${SCW_CONFIG}" | jq -r --arg p "\${SCW_PROFILE}" '.profiles[\$p].access_key')"
export AWS_SECRET_ACCESS_KEY="\$(echo "\${SCW_CONFIG}" | jq -r --arg p "\${SCW_PROFILE}" '.profiles[\$p].secret_key')"

# Pulumi passphrase from Scaleway Secrets Manager
export PULUMI_CONFIG_PASSPHRASE="\$(scw secret version access ${SECRET_ID} revision=latest region=${REGION} -o json | jq -r '.data' | base64 -d)"

# Pulumi backend
export PULUMI_BACKEND_URL="s3://${BUCKET_NAME}?endpoint=${S3_ENDPOINT}&region=${REGION}"
EOF

echo "    .envrc written."

echo ""
echo "==> Setup complete!"
echo "    Next steps:"
echo "      1. Run 'direnv allow'"
echo "      2. Run 'pulumi login' (reads PULUMI_BACKEND_URL from .envrc)"
