apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: platform-pv-${NAMESPACE}
  resources:
    requests:
      storage: 1Gi
