// AUTO-GENERATED by tooling/openapi-codegen.
// Source: cargo run -p familiar-systems-platform --bin emit-openapi
// Do not edit by hand. Run `mise run generate-types` to refresh.

import type { CampaignId, MeResponse, UserId } from "@familiar-systems/types-app";
export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Format: nanoid
     * @description Identifies a campaign. Kept as a nanoid for short URLs.
     */
    CampaignId: CampaignId;
    /**
     * @description Response body for `GET /me`.
     *
     *     **Wire format we own (API contract with the SPA).** Exported to TypeScript
     *     as `MeResponse` via ts-rs. Changes are breaking changes to the frontend.
     *
     *     `id` is the Hanko subject (= `users.id`); see
     *     `apps/platform/src/entities/users.rs`.
     */
    MeResponse: MeResponse;
    /**
     * Format: uuid
     * @description Uniquely identifies a user.
     */
    UserId: UserId;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authenticated user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
