apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mgrinshpon@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
      - dns01:
          webhook:
            groupName: com.bunny.webhook
            solverName: bunny
            config:
              secretRef: bunny-api-key
              secretNamespace: cert-manager
