// AUTO-GENERATED by tooling/openapi-codegen.
// Source: cargo run -p familiar-systems-campaign --bin emit-openapi-campaign
// Do not edit by hand. Run `mise run generate-types` to refresh.

import type {
  AudioMode,
  ByoEntry,
  CatalogResponse,
  InitializeErrorResponse,
  InitializeRequest,
  SystemEntry,
  TemplateRef,
} from "@familiar-systems/types-campaign";
export interface paths {
  "/campaign/{id}/initialize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["initialize"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/catalog/systems": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_systems"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness-style health endpoint. Returns 200 with `ready` body while
     *     the registry is in `Phase::Ready`; once drain has begun, returns 503
     *     with `draining`. k8s readiness probes consume the status code to
     *     take the pod out of the LB rotation immediately when drain starts,
     *     so the platform's `/internal/campaign/init` calls stop being routed
     *     here before in-flight requests finish. If the registry itself is
     *     unreachable (mailbox closed or actor crashed), returns 503 with
     *     `registry_unavailable`.
     */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Audio capture / training mode chosen during the wizard.
     *
     *     Three states modeled as a sum type, not a `bool` pair, so the FE
     *     can't accidentally produce "no recording but train on it" or other
     *     nonsense combinations.
     * @enum {string}
     */
    AudioMode: AudioMode;
    ByoEntry: ByoEntry;
    CatalogResponse: CatalogResponse;
    /**
     * @description Returned on the deliberate failure path of v0. The FE renders `error`
     *     inline and surfaces `campaign_id` so the user can find their (broken)
     *     campaign back in the hub.
     */
    InitializeErrorResponse: InitializeErrorResponse;
    InitializeRequest: InitializeRequest;
    SystemEntry: SystemEntry;
    TemplateRef: TemplateRef;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  initialize: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Campaign ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InitializeRequest"];
      };
    };
    responses: {
      /** @description Campaign initialized */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Already initialized */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Initialization failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InitializeErrorResponse"];
        };
      };
    };
  };
  list_systems: {
    parameters: {
      query?: {
        locale?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Locale-resolved game system catalog */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Draining or unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
