// AUTO-GENERATED by tooling/openapi-codegen.
// Source: cargo run -p familiar-systems-campaign --bin emit-openapi-campaign
// Do not edit by hand. Run `mise run generate-types` to refresh.

import type {
  AudioMode,
  ByoEntry,
  CampaignErrorResponse,
  CampaignMetadataResponse,
  CatalogResponse,
  CreatePageRequest,
  PageId,
  PageKind,
  PageResponse,
  PatchCampaignRequest,
  Status,
  SystemEntry,
  TemplateRef,
} from "@familiar-systems/types-campaign";
export interface paths {
  "/campaign/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_campaign"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["patch_campaign"];
    trace?: never;
  };
  "/campaign/{id}/pages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_page"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/catalog/systems": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_systems"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness-style health endpoint. Returns 200 with `ready` body while
     *     the registry is in `Phase::Ready`; once drain has begun, returns 503
     *     with `draining`. k8s readiness probes consume the status code to
     *     take the pod out of the LB rotation immediately when drain starts,
     *     so the platform's `/internal/campaign/init` calls stop being routed
     *     here before in-flight requests finish. If the registry itself is
     *     unreachable (mailbox closed or actor crashed), returns 503 with
     *     `registry_unavailable`.
     */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Audio capture / training mode chosen during the wizard.
     *
     *     Three states modeled as a sum type, not a `bool` pair, so the FE
     *     can't accidentally produce "no recording but train on it" or other
     *     nonsense combinations.
     * @enum {string}
     */
    AudioMode: AudioMode;
    ByoEntry: ByoEntry;
    CampaignErrorResponse: CampaignErrorResponse;
    CampaignMetadataResponse: CampaignMetadataResponse;
    CatalogResponse: CatalogResponse;
    /**
     * @description Create a new Page in a campaign.
     *
     *     `name` is required; everything else is optional. A missing `status` defaults
     *     to `gmOnly` (the domain default for new content). `parent` places the Page
     *     in the table of contents: omitted appends it at the ToC root; `Some(id)`
     *     nests it as the last child of that Page's ToC node. `from_template_id` is
     *     accepted but not yet implemented (the server returns 501).
     */
    CreatePageRequest: CreatePageRequest;
    /**
     * Format: ulid
     * @description Uniquely identifies a page (NPC, location, item, etc.).
     *     ULID for compact URLs (26 chars) and B-tree-friendly insert ordering.
     */
    PageId: PageId;
    /**
     * @description What kind of Page this is: its document *structure* and the systemic actions
     *     the engine takes for it. A `kind` exists only when pages differ structurally
     *     (a different Loro schema) or need a systemic action the engine can't infer
     *     from content; editorial differences (NPC vs Location) live in tags,
     *     relationships, and template lineage, not here.
     *     See
     *     - docs/plans/2026-03-25-ai-serialization-format-v2.md
     *     - docs/glossary.md
     *     - issue #155.
     *
     *     Only `Entity` and `Template` exist today. `Session`, `Skill`, and `Memory`
     *     are known future cases (the audio pipeline and the agent system) and get
     *     added as variants when those documents are actually built - each addition
     *     makes the `match` arms below non-exhaustive, so the compiler points at
     *     every site.
     * @enum {string}
     */
    PageKind: PageKind;
    /** @description A created Page, returned with `201 Created`. */
    PageResponse: PageResponse;
    PatchCampaignRequest: PatchCampaignRequest;
    /**
     * @description Visibility status for campaign content. The CRDT syncs all content to all
     *     clients regardless of status; consumers (the browser UI, AI conversations)
     *     filter what they surface based on the user's role.
     *     See: docs/plans/2026-02-22-ai-prd.md
     * @enum {string}
     */
    Status: Status;
    SystemEntry: SystemEntry;
    TemplateRef: TemplateRef;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_campaign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Campaign ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Campaign metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CampaignMetadataResponse"];
        };
      };
      /** @description Missing or invalid session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not the campaign owner */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Campaign not on this shard */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Server restarting */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patch_campaign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Campaign ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchCampaignRequest"];
      };
    };
    responses: {
      /** @description Campaign updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CampaignMetadataResponse"];
        };
      };
      /** @description Missing or invalid session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not the campaign owner */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Campaign not on this shard */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Wizard already completed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Required fields missing for wizard completion */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Update failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CampaignErrorResponse"];
        };
      };
    };
  };
  create_page: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Campaign ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePageRequest"];
      };
    };
    responses: {
      /** @description Page created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PageResponse"];
        };
      };
      /** @description Missing or invalid session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Caller is not a GM of this campaign */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Campaign not on this shard */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Parent page not found, or the page name is empty */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Creation failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Creating from a template is not yet supported */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Server restarting or platform unreachable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_systems: {
    parameters: {
      query?: {
        locale?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Locale-resolved game system catalog */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Draining or unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
