use chrono::{DateTime, Utc};
use familiar_systems_app_shared::id::{CampaignId, UserId};
use fs_id::Uuid;
use sea_orm::entity::prelude::*;

use crate::entities::columns::PageIdCol;

#[derive(Debug, Clone, PartialEq, Eq, Hash, DeriveValueType)]
#[sea_orm(column_type = "Text")]
pub struct CampaignIdCol(pub String);

impl From<CampaignId> for CampaignIdCol {
    fn from(id: CampaignId) -> Self {
        Self(id.0.into())
    }
}

impl From<CampaignIdCol> for CampaignId {
    fn from(col: CampaignIdCol) -> Self {
        Self(col.0.into())
    }
}

pub const METADATA_ROW_ID: i32 = 1;

/// Campaign metadata is a per-campaign summary of everything about that campaign.
/// At time of writing, it's mostly used for display purposes.
/// In the future, this would be an excellent place for pages like feature flags.
#[derive(Debug, Clone, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "campaign_metadata")]
pub struct Model {
    /// Always [`METADATA_ROW_ID`]. Singleton table; the migration enforces
    /// `CHECK (id = 1)` at the DB level.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,

    /// The campaign ID generated by platform when creating a campaign
    pub campaign_id: CampaignIdCol,
    /// Hanko subject UUID of the campaign owner, set at checkout time.
    #[sea_orm(column_type = "Text")]
    pub owner_user_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub tagline: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_system: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_locale: Option<String>,
    /// Pointer to the campaign's home / landing-page Page, seeded once at
    /// creation ("Campaign Base Camp"). FK to `pages(id)` with
    /// `ON DELETE SET NULL` (see [`Relation::HomePage`]): deleting the Page
    /// clears the pointer rather than the campaign row, so a non-null value
    /// always resolves to a live Page. Null only in the brief window before
    /// the async seed completes.
    pub home_page_id: Option<PageIdCol>,
    pub wizard_completed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Model {
    pub fn is_owned_by(&self, user: &UserId) -> bool {
        Uuid::parse_str(&self.owner_user_id)
            .map(|stored| stored == user.0)
            .unwrap_or(false)
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Soft reference to the home / landing-page Page. `ON DELETE SET NULL`
    /// so deleting the Page clears the pointer instead of cascading into the
    /// singleton campaign row. Mirrors the FK declared in the create migration;
    /// `schema_drift` asserts the two stay in lockstep.
    #[sea_orm(
        belongs_to = "super::pages::Entity",
        from = "Column::HomePageId",
        to = "super::pages::Column::Id",
        on_delete = "SetNull"
    )]
    HomePage,
}

impl ActiveModelBehavior for ActiveModel {}
