use chrono::{DateTime, Utc};
use familiar_systems_app_shared::id::CampaignId;
use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, Hash, DeriveValueType)]
#[sea_orm(column_type = "Text")]
pub struct CampaignIdCol(pub String);

impl From<CampaignId> for CampaignIdCol {
    fn from(id: CampaignId) -> Self {
        Self(id.0)
    }
}

impl From<CampaignIdCol> for CampaignId {
    fn from(col: CampaignIdCol) -> Self {
        Self(col.0)
    }
}

/// Campaign metadata is a per-campaign summary of everything about that campaign.
/// At time of writing, it's mostly used for display purposes.
/// In the future, this would be an excellent place for things like feature flags.
#[derive(Debug, Clone, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "campaign_metadata")]
pub struct Model {
    /// Always 1. This is a singleton table; the migration enforces a
    /// `CHECK (id = 1)` constraint at the DB level. (`extra = "..."` is not a
    /// recognized sea-orm attribute in 1.1, so the constraint cannot be
    /// declared here - the migration is the source of truth.)
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,

    /// The campaign ID generated by platform when creating a campaign
    pub campaign_id: CampaignIdCol,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
