# Generated by scripts/generate-imports.sh from Pulumi state export.
# Delete this file after running: tofu apply -var-file=prod.tfvars

# --- Hetzner Cloud ---

import {
  to = hcloud_ssh_key.personal
  id = "108804866"
}

import {
  to = hcloud_ssh_key.deploy
  id = "108804710"
}

import {
  to = hcloud_floating_ip.main
  id = "122411370"
}

import {
  to = hcloud_firewall.main
  id = "10670666"
}

import {
  to = hcloud_volume.data
  id = "105151425"
}

import {
  to = hcloud_server.k3s
  id = "124161540"
}

import {
  to = hcloud_floating_ip_assignment.main
  id = "122411370"
}

import {
  to = hcloud_volume_attachment.data
  id = "105151425"
}

# --- Scaleway IAM ---

import {
  to = scaleway_registry_namespace.main
  id = "fr-par/82a2192c-f39a-4659-8684-edba8449cdc3"
}

import {
  to = scaleway_iam_application.registry_pull
  id = "608f53a5-6141-43fc-a63c-c8727642843a"
}

import {
  to = scaleway_iam_application.eso
  id = "2e3c052e-aac5-4aa3-9c69-fa429fc0ca75"
}

import {
  to = scaleway_iam_policy.registry_pull
  id = "7757f9e9-2154-4e94-98d1-a4392441d9c2"
}

import {
  to = scaleway_iam_policy.eso
  id = "dd6f57df-4f38-41db-aa49-d24d681f4eed"
}

import {
  to = scaleway_iam_api_key.registry_pull
  id = "SCWANWQ2BE9AB5CWZ8DM"
}

import {
  to = scaleway_iam_api_key.eso
  id = "SCWCW30AE87TNAM34VPH"
}

# --- Scaleway Secrets ---

import {
  to = scaleway_secret.deploy_ssh
  id = "fr-par/a924690f-ca5e-445b-9fd0-16c857deba33"
}

import {
  to = scaleway_secret.bunny_api_key
  id = "fr-par/e1660403-0d32-4110-9683-a2225622b84f"
}

import {
  to = scaleway_secret.k3s_kubeconfig
  id = "fr-par/9dc8cfec-0d60-4ab7-b251-ec16e9309f10"
}

import {
  to = scaleway_secret.internal_bearer_prod
  id = "fr-par/ee8ab99c-bc31-4425-b09f-923cfc4a15c9"
}

import {
  to = scaleway_secret.internal_bearer_preview
  id = "fr-par/aef493cd-6e8a-499e-8f7c-c24bf0221da7"
}

import {
  to = scaleway_secret.eso_credential
  id = "fr-par/1a1aa0cf-cbae-4fdb-b4f4-e50e58ab5270"
}

import {
  to = scaleway_secret.registry_pull_credential
  id = "fr-par/8c8dd4e7-d24e-4b2c-a18c-041aa3c8cc6d"
}

import {
  to = scaleway_secret_version.eso_credential
  id = "fr-par/1a1aa0cf-cbae-4fdb-b4f4-e50e58ab5270/1"
}

import {
  to = scaleway_secret_version.registry_pull_credential
  id = "fr-par/8c8dd4e7-d24e-4b2c-a18c-041aa3c8cc6d/1"
}

# --- Hetzner Object Storage (minio) ---

import {
  to = minio_s3_bucket.prod
  id = "familiar-systems-prod"
}

import {
  to = minio_s3_bucket.preview
  id = "familiar-systems-preview"
}

import {
  to = minio_s3_bucket_policy.prod
  id = "familiar-systems-prod"
}

import {
  to = minio_s3_bucket_policy.preview
  id = "familiar-systems-preview"
}

import {
  to = minio_s3_bucket_versioning.prod
  id = "familiar-systems-prod"
}

import {
  to = minio_ilm_policy.prod
  id = "familiar-systems-prod"
}

import {
  to = minio_ilm_policy.preview
  id = "familiar-systems-preview"
}

import {
  to = scaleway_secret.hcloud_api_token
  id = "fr-par/3f8e128b-f97b-418a-a9ef-f6d3e43f7ae7"
}
